services:
  web:
    container_name: web
    # image: nonnicha007/register-form-ror:latest
    build: .
    volumes:
      - .:/rails
    ports:
      - "80:3000"
    environment:
      - RAILS_ENV=development
      - RAILS_MASTER_KEY=804101aa5a417ca52c9824f5a59a6111
      - SECRET_KEY_BASE=$(bundle exec rails secret)
    command: bash -c "bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails server -p '3000' -b '0.0.0.0'"